# Base component API configuration
__merge__: ../../api/comp_metric.yaml

# Component configuration
name: distance_correlation
info:
  metrics:
    - name: waypoint_distance_correlation
      label: Waypoint Distance Correlation
      summary: "Calculates the distance correlation by computing Spearman correlations between distances to waypoint cells."
      description: |
        Calculates the distance correlation by computing Spearman correlations
        between distances to waypoint cells on the full (or processed) data
        matrix and the dimensionally-reduced matrix."
      references:
        doi: 10.1007/bf02289565
      min: -1
      max: 1
      maximize: true
    - name: centroid_distance_correlation
      label: Centroid Distance Correlation
      summary: "Calculates the distance correlation by computing Spearman correlations between distances to label centroids."
      description: |
        Calculates the distance correlation by computing Spearman correlations
        between distances to label centroids on the full (or processed) data
        matrix and the dimensionally-reduced matrix."
      references:
        doi: 10.1007/bf02289565
      min: -1
      max: 1
      maximize: true

# Script configuration
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - scikit-learn
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, midcpu]
